-- MySQL Script generated by MySQL Workbench
-- Wed Jan 31 21:06:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Person`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Person` (
  `person_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `address` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`person_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Location_Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Location_Type` (
  `location_type_id` INT NOT NULL,
  `location_name` VARCHAR(45) NULL,
  PRIMARY KEY (`location_type_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Waste_producer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Waste_producer` (
  `gps_latitude` VARCHAR(45) NULL,
  `gps_longitude` VARCHAR(45) NULL,
  `waste_producer_id` INT NOT NULL,
  `location_type_id` INT NOT NULL,
  `subscription_status` VARCHAR(45) NULL,
  `subscription_period` VARCHAR(45) NULL,
  PRIMARY KEY (`waste_producer_id`),
  INDEX `fk_Waste_producer_Location_Type1_idx` (`location_type_id` ASC),
  CONSTRAINT `fk_Waste_producer_Person1`
    FOREIGN KEY (`waste_producer_id`)
    REFERENCES `mydb`.`Person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Waste_producer_Location_Type1`
    FOREIGN KEY (`location_type_id`)
    REFERENCES `mydb`.`Location_Type` (`location_type_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Collection_Agent`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Collection_Agent` (
  `collection_agent_id` INT NOT NULL,
  `Area` VARCHAR(45) NULL,
  PRIMARY KEY (`collection_agent_id`),
  INDEX `fk_Collection_Agent_Person1_idx` (`collection_agent_id` ASC),
  CONSTRAINT `fk_Collection_Agent_Person1`
    FOREIGN KEY (`collection_agent_id`)
    REFERENCES `mydb`.`Person` (`person_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Task`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Task` (
  `idTask` INT NOT NULL,
  `Date` VARCHAR(45) NULL,
  `Status` VARCHAR(45) NULL,
  `collection_agent_id` INT NOT NULL,
  PRIMARY KEY (`idTask`),
  INDEX `fk_Task_Collection_Agent1_idx` (`collection_agent_id` ASC),
  CONSTRAINT `fk_Task_Collection_Agent1`
    FOREIGN KEY (`collection_agent_id`)
    REFERENCES `mydb`.`Collection_Agent` (`collection_agent_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Task_Location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Task_Location` (
  `idTask_Location` INT NOT NULL,
  `idWaste_Producer` VARCHAR(45) NULL,
  `Task_idTask` INT NOT NULL,
  PRIMARY KEY (`idTask_Location`),
  INDEX `fk_Task_Location_Task1_idx` (`Task_idTask` ASC),
  CONSTRAINT `fk_Task_Location_Task1`
    FOREIGN KEY (`Task_idTask`)
    REFERENCES `mydb`.`Task` (`idTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Task_Waste_Producer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Task_Waste_Producer` (
  `task_id` INT NOT NULL,
  `waste_producer_id` INT NOT NULL,
  `Task_idTask` INT NOT NULL,
  PRIMARY KEY (`task_id`, `waste_producer_id`, `Task_idTask`),
  INDEX `fk_Task_Waste_Producer_Task1` (`task_id` ASC),
  INDEX `fk_Task_Waste_Producer_Waste_producer1_idx` (`waste_producer_id` ASC),
  INDEX `fk_Task_Waste_Producer_Task1_idx` (`Task_idTask` ASC),
  CONSTRAINT `fk_Task_Waste_Producer_Waste_producer1`
    FOREIGN KEY (`waste_producer_id`)
    REFERENCES `mydb`.`Waste_producer` (`waste_producer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Task_Waste_Producer_Task1`
    FOREIGN KEY (`Task_idTask`)
    REFERENCES `mydb`.`Task` (`idTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
